In [1]:
import matplotlib.pyplot as plt
import numpy as np
import astropy.constants as c
import astropy.units as u

In [2]:
def Stellar_Mass_Ks(kmag,parallax): # Mann+ 2019
    
    a = np.array([-0.647,-0.208,-8.43e-4,7.87e-3,1.42e-4,-2.13e-4])
    i = np.array([0,1,2,3,4,5])
    
    Kmag = kmag - 5*np.log10(parallax/10)
    mass_integral = a*((Kmag-7.5)**i)
    Mass = np.sum(mass_integral)
    return 10**Mass # errors are 5%

In [3]:
def Stellar_Radius_Teff(T_eff): # Mann+ 2015, eqn 4
    
    a = 10.544
    b = -33.7546
    c = 35.1909
    d = -11.5928
    
    X = T_eff/3500
    
    Radius = a + b*X + c*X**2 + d*X**3
    
    return Radius # 14% error

In [4]:
def Stellar_Radius_Ks(kmag,parallax): # Mann+ 2015, eqn 4
    
    a = 1.9515
    b = -0.352
    c = 0.0168
    Kmag = kmag - 5*np.log10(parallax/10)
    radius = a + b*Kmag +c*Kmag**2.0
    return radius # 5% error

In [5]:
def Stellar_Teff_VJH(v,j,h): # Mann+ 2015

    X = v-j 
    a = 2.769 
    b = -1.421
    c = 0.4284
    d = -0.06133
    e = 0.003310
    f = 0.1333
    g = -0.05416
    Teff = a + b*(X) + c*(X**2) + d*(X**3) + e*(X**4) + f*((j-h)) + g*((j-h)**2)
    return Teff*3500

In [6]:
def Stellar_Teff_VIc(v,ic): # Mann+ 2015

    X = v-ic
    a = 2.455
    b = -1.5701
    c = 0.6891
    d = -0.15
    e = 0.01254
    Teff = a + b*(X) + c*(X**2) + d*(X**3) + e*(X**4)
    
    return Teff*3500

In [7]:
def Stellar_Teff_VJ(v,j): # Mann+ 2015
    
    X = v-j
    a = 2.84
    b = -1.3453
    c = 0.3906
    d = -0.0546
    e = 0.002913
    Teff = a + b*(X) + c*(X**2) + d*(X**3) + e*(X**4)
    
    return Teff*3500

In [8]:
def Bolometric_Correction_Lum(v, j, parallax):
    
    #sigma = +/- 0.016, or 5% (inflated from 2-3%)
    
    a = 0.5817
    b = -0.4168
    c = -0.08165
    d = 4.084e-3
    
    X = v-j
    Distance = parallax/10
    V = v - 5*np.log10(Distance)
    
    BCv = a + b*(X) + c*(X**2) + d*(X**3)
    mbol = v + BCv
    Mbol = mbol - 5*np.log10(Distance)
    Msun = 4.8
    
    lum = 10**((Msun-Mbol)/2.5)
    
    return lum

In [9]:
def Luminosity(R,Teff):
    
    L = R**2*(Teff/5770)**4
    return L

In [10]:
def Density(M,R):
    
    Mass = M*c.M_sun * (1000*u.g/u.kg)
    volume = 4/3*np.pi*(R*c.R_sun)**3 * (100*u.cm/u.m)**3
    density = Mass/volume
    
    return density

## TOI 203


In [11]:
Stellar_Mass_Ks(9.722,24.8)

0.20004334259636225

In [12]:
Stellar_Radius_Ks(9.722,24.8)

0.23257367094018844

In [14]:
Stellar_Teff_VJH(15.02,10.56,10.05)

3064.246519157603

### TOI 237

In [98]:
Bolometric_Correction_Lum(16.37,11.74,38.11)

0.004086026704677663

In [99]:
luminosities = Luminosity(np.random.normal(0.211,0.016,1000),
                          np.random.normal(3160,60,1000))
np.percentile(luminosities,[16.,50.,84.])

array([0.0033452 , 0.00402592, 0.00477037])

In [100]:
Stellar_Mass_Ks(10.896,38.11)

0.17850158640890543

In [101]:
Stellar_Radius_Ks(10.896,38.11)

0.2114664230169081

In [102]:
#Stellar_Radius_Teff(3160)

In [103]:
Stellar_Teff_VJH(16.37,11.74,11.19)

3024.6023836668487

In [104]:
Stellar_Teff_VJ(16.37,11.74)

3163.8274476547535

In [116]:
dens = Density(np.random.normal(0.179,0.009,10000),np.random.normal(0.211,0.011,10000))
np.percentile(dens,[16.,50.,84.])

array([22.97596378, 27.01276583, 31.6783442 ])

In [105]:
# plt.figure(figsize=(8,8))
# plt.xlim(0.1,0.5)
# plt.xlabel('Mass (Msun)')
# plt.ylim(0.1,0.5)
# plt.ylabel('Radius (Rsun)')

# plt.axvspan(0.17,0.188, label='Mann+ 2019 (MKs)',color='black',alpha=0.3)
# plt.axhspan((0.183),(0.203), label='Mann+ 2015 (Teff=3085K)',color='hotpink',alpha=0.3)
# plt.axhspan((0.2),(0.222), label='Mann+ 2015 (MKs)',color='b',alpha=0.3)
# plt.axhspan((0.24),(0.32), label='Magellan FIRE',color='orange', alpha=0.3)
# plt.axhspan((0.195),(0.219), label='Michele Silversteins Pipeline',color='green',alpha=0.3)

# plt.plot(Masses_from_Mann2019/c.M_sun,radii_from_density,color='k',
#          label=r'Radius based on $\rho_{*}$')

# plt.legend()
# plt.show()

In [106]:
# plt.figure(figsize=(8,8))
# plt.xlim(2800,3900)
# plt.xlabel('Teff (K)')
# plt.ylim(0.1,0.5)
# plt.ylabel('Radius (Rsun)')

# plt.axhspan((0.183),(0.203), label='Mann+ 2015 (Teff=3085K)',color='blue',alpha=0.3)
# plt.axhspan((0.2),(0.222), label='Mann+ 2015 (MKs)',color='red',alpha=0.3)

# plt.axhspan((0.24),(0.32), label='Magellan FIRE',color='orange', alpha=0.3)
# plt.axvspan((2998),(3172),color='orange', alpha=0.3)

# plt.axhspan((0.195),(0.219), label='Michele Silversteins Pipeline',color='green',alpha=0.3)
# plt.axvspan((3073),(3255),color='green', alpha=0.3)

# plt.errorbar()

# plt.axvspan((2900),(3100), label='SALT HRS',color='hotpink', alpha=0.3)
# plt.axvspan((2874),(3176), label='Mann+ 2015 (VJH)',color='k', alpha=0.3)

# plt.legend()
# plt.show()

## TOI 122

In [107]:
Bolometric_Correction_Lum(15.526,11.531,62.12)

0.014012798748905705

In [120]:
luminosities = Luminosity(np.random.normal(0.334,0.017,10000),
                          np.random.normal(3360,60,10000))
np.percentile(luminosities,[16.,50.,84.])

array([0.01131071, 0.0128131 , 0.01445402])

In [119]:
#Stellar_Radius_Teff(3360)

In [25]:
Stellar_Radius_Ks(10.771,62.12)

0.33413421570192503

In [21]:
Stellar_Mass_Ks(10.771,62.12)

0.3123268329641512

In [18]:
Stellar_Teff_VJH(15.526,11.531,11.02)

3206.2297494091144

In [26]:
Stellar_Teff_VJ(15.526,11.531)

3360.7218302028728

In [118]:
dens = Density(np.random.normal(0.312,0.016,10000),np.random.normal(0.334,0.017,10000))
np.percentile(dens,[16.,50.,84.])

array([10.09307007, 11.8180517 , 13.93551821])

In [22]:
# plt.figure(figsize=(8,8))
# plt.xlim(0.1,0.5)
# plt.xlabel('Mass (Msun)')
# plt.ylim(0.1,0.5)
# plt.ylabel('Radius (Rsun)')

# plt.axvspan(0.296,0.328, label='Mann+ 2019 (MKs)',color='black',alpha=0.3)
# plt.axhspan((0.483),(0.533), label='Mann+ 2015 (Teff=3732K)',color='hotpink',alpha=0.3)
# plt.axhspan(0.317,0.351, label='Mann+ 2015 (MKs)',color='b',alpha=0.3)
# plt.axhspan((0.41),(0.47), label='Magellan FIRE',color='orange', alpha=0.3)
# plt.axhspan((0.316),(0.354), label='Michele Silversteins Pipeline',color='green',alpha=0.3)

# plt.plot(Masses_from_Mann2019/c.M_sun,radii_from_density,color='k',
#          label=r'Radius based on $\rho_{*}$')

# plt.legend()
# plt.show()

In [23]:
# plt.figure(figsize=(8,8))
# plt.xlim(3000,4000)
# plt.xlabel('Teff (K)')
# plt.ylim(0.1,0.5)
# plt.ylabel('Radius (Rsun)')

# plt.axhspan((0.483),(0.533), label='Mann+ 2015 (Teff=3732K)',color='hotpink',alpha=0.3)
# plt.axhspan(0.317,0.351, label='Mann+ 2015 (MKs)',color='b',alpha=0.3)

# plt.axhspan((0.41),(0.47), label='Magellan FIRE',color='orange', alpha=0.3)
# plt.axvspan((3647),(3817), label='Magellan FIRE',color='orange')

# plt.axvspan((3600),(3800), label='SALT HRS',color='blue')

# plt.axvspan((3046),(3356), label='Mann+ 2015 (VJH)',color='purple')

# plt.axhspan((0.316),(0.354), label='Michele Silversteins Pipeline',color='green',alpha=0.3)
# plt.axvspan((3276),(3462),color='green')

# plt.legend()
# plt.show()